apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
        - name: maven-app
          image: rferns/maven-app:latest
          imagePullPolicy: Always

          # Keep container alive
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep infinity

          # Print Hello World once, without restart
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    echo "Hello World"
